//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioStudioDAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Cita
    {
        public int Id { get; set; }

        [DisplayName("Sala")]
        public Nullable<int> IdSala { get; set; }

        [Required(ErrorMessage = "El Nombre es requerido")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El Nombre es requerido")]
        public string Apellido { get; set; }

        [DisplayName("Celular")]
        public string Cel { get; set; }

        [DisplayName("Fecha y hora de inicio")]
        [Required(ErrorMessage = "La Fecha y hora de inicio es requerida")]
        [DataType("datetime-local")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaHoraInico { get; set; }

        [DisplayName("Fecha y hora de finalización")]
        [Required(ErrorMessage = "La Fecha y hora de finalización es requerida")]
        [DataType("datetime-local")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaHoraFin { get; set; }

        [Required(ErrorMessage = "El correo es reuqerido")]
        [EmailAddress(ErrorMessage = "El correo no tiene el formato correcto")]
        public string Correo { get; set; }

     
        public virtual Sala Sala { get; set; }
    }
}
