//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioStudioDAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Inventario
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "El Tipo de elemento es requerido")]
        [DisplayName("Tipo de elemento")]
        public int IdTipo { get; set; }

        [Required(ErrorMessage = "La sala es requerido")]
        [DisplayName("Sala")]
        public int IdSala { get; set; }

        [Required(ErrorMessage = "La marca es requerido")]
        public string Marca { get; set; }

        public string Procesador { get; set; }

        [DisplayName("Disco duro")]
        public string DiscoDuro { get; set; }

        [DisplayName("Memoria RAM")]
        public string Ram { get; set; }
        public string Serial { get; set; }
        public string Observacion { get; set; }
    
        public virtual Sala Sala { get; set; }
        public virtual Tipo Tipo { get; set; }
    }
}
